openapi: 3.0.0
info:
  title: SGD api
  description: Documentação da api rest sgd  `AUTH BEARER-TOKEN`.
  version: 1.0.0

servers:
  - url: http://127.0.0.1:8000/api/v1
    description: Servidor de desenvolvimento

paths:
  /login:
    post:
      summary: Autenticar usuário
      description: Este endpoint permite que os usuários façam login na API.
      requestBody:
        content:
          application/json:
            example: 
              username: exemplo
              password: senha
      responses:
        200:
          description: Login bem-sucedido
          content:
            application/json:
              example:
                message: Login bem-sucedido
                token: token_de_autenticação
        401:
          description: Falha na autenticação

  /logout:
    post:
      summary: Encerrar sessão
      description: Este endpoint permite que os usuários façam logout da API.
      responses:
        200:
          description: Logout bem-sucedido
        401:
          description: Falha na autenticação

  /users:
    get:
      summary: Listar usuários
      description: Este endpoint lista todos os usuários.
      responses:
        200:
          description: Lista de usuários
          content:
            application/json:
              example:
                users:
                  - id: 1
                    name: Usuário 1
                  - id: 2
                    name: Usuário 2
        401:
          description: Falha na autenticação

  /user/{user}:
    get:
      summary: Obter usuário por ID
      description: Este endpoint recupera um usuário pelo seu ID.
      parameters:
        - in: path
          name: user
          required: true
          schema:
            type: integer
          description: ID do usuário a ser recuperado
      responses:
        200:
          description: Dados do usuário
          content:
            application/json:
              example:
                id: 1
                name: Usuário 1
        401:
          description: Falha na autenticação
        404:
          description: Usuário não encontrado

    put:
      summary: Atualizar usuário
      description: Este endpoint atualiza os detalhes de um usuário existente.
      parameters:
        - in: path
          name: user
          required: true
          schema:
            type: integer
          description: ID do usuário a ser atualizado
      requestBody:
        content:
          application/json:
            example:
              name: Novo Nome
      responses:
        200:
          description: Usuário atualizado
        401:
          description: Falha na autenticação
        404:
          description: Usuário não encontrado

    delete:
      summary: Excluir usuário
      description: Este endpoint exclui um usuário existente.
      parameters:
        - in: path
          name: user
          required: true
          schema:
            type: integer
          description: ID do usuário a ser excluído
      responses:
        200:
          description: Usuário excluído
        401:
          description: Falha na autenticação
        404:
          description: Usuário não encontrado

  /customers:
    get:
      summary: Listar clientes
      description: Este endpoint lista todos os clientes.
      responses:
        200:
          description: Lista de clientes
          content:
            application/json:
              example:
                customers:
                  - id: 1
                    name: Cliente 1
                  - id: 2
                    name: Cliente 2
        401:
          description: Falha na autenticação

  /customer/{customer}:
    get:
      summary: Obter cliente por ID
      description: Este endpoint recupera um cliente pelo seu ID.
      parameters:
        - in: path
          name: customer
          required: true
          schema:
            type: integer
          description: ID do cliente a ser recuperado
      responses:
        200:
          description: Dados do cliente
          content:
            application/json:
              example:
                id: 1
                name: Cliente 1
        401:
          description: Falha na autenticação
        404:
          description: Cliente não encontrado

    post:
      summary: Criar cliente
      description: Este endpoint cria um novo cliente.
      requestBody:
        content:
          application/json:
            example:
              name: Novo Cliente
      responses:
        201:
          description: Cliente criado com sucesso
          content:
            application/json:
              example:
                message: Cliente criado com sucesso
                customer_id: 3
        401:
          description: Falha na autenticação

    put:
      summary: Atualizar cliente
      description: Este endpoint atualiza os detalhes de um cliente existente.
      parameters:
        - in: path
          name: customer
          required: true
          schema:
            type: integer
          description: ID do cliente a ser atualizado
      requestBody:
        content:
          application/json:
            example:
              name: Novo Nome do Cliente
      responses:
        200:
          description: Cliente atualizado
          content:
            application/json:
              example:
                message: Cliente atualizado com sucesso
        401:
          description: Falha na autenticação
        404:
          description: Cliente não encontrado

    delete:
      summary: Excluir cliente
      description: Este endpoint exclui um cliente existente.
      parameters:
        - in: path
          name: customer
          required: true
          schema:
            type: integer
          description: ID do cliente a ser excluído
      responses:
        200:
          description: Cliente excluído
          content:
            application/json:
              example:
                message: Cliente excluído com sucesso
        401:
          description: Falha na autenticação
        404:
          description: Cliente não encontrado

  /products:
    get:
      summary: Listar produtos
      description: Este endpoint lista todos os produtos.
      responses:
        200:
          description: Lista de produtos
          content:
            application/json:
              example:
                products:
                  - id: 1
                    name: Produto 1
                  - id: 2
                    name: Produto 2
        401:
          description: Falha na autenticação

  /product/{product}:
    get:
      summary: Obter produto por ID
      description: Este endpoint recupera um produto pelo seu ID.
      parameters:
        - in: path
          name: product
          required: true
          schema:
            type: integer
          description: ID do produto a ser recuperado
      responses:
        200:
          description: Dados do produto
          content:
            application/json:
              example:
                id: 1
                name: Produto 1
        401:
          description: Falha na autenticação
        404:
          description: Produto não encontrado

    post:
      summary: Criar produto
      description: Este endpoint cria um novo produto.
      requestBody:
        content:
          application/json:
            example:
              name: Novo Produto
      responses:
        201:
          description: Produto criado com sucesso
          content:
            application/json:
              example:
                message: Produto criado com sucesso
                product_id: 3
        401:
          description: Falha na autenticação

    put:
      summary: Atualizar produto
      description: Este endpoint atualiza os detalhes de um produto existente.
      parameters:
        - in: path
          name: product
          required: true
          schema:
            type: integer
          description: ID do produto a ser atualizado
      requestBody:
        content:
          application/json:
            example:
              name: Novo Nome do Produto
      responses:
        200:
          description: Produto atualizado
          content:
            application/json:
              example:
                message: Produto atualizado com sucesso
        401:
          description: Falha na autenticação
        404:
          description: Produto não encontrado

    delete:
      summary: Excluir produto
      description: Este endpoint exclui um produto existente.
      parameters:
        - in: path
          name: product
          required: true
          schema:
            type: integer
          description: ID do produto a ser excluído
      responses:
        200:
          description: Produto excluído
          content:
            application/json:
              example:
                message: Produto excluído com sucesso
        401:
          description: Falha na autenticação
        404:
          description: Produto não encontrado

  /order-requests:
    get:
      summary: Listar solicitações de pedidos
      description: Este endpoint lista todas as solicitações de pedidos.
      responses:
        200:
          description: Lista de solicitações de pedidos
          content:
            application/json:
              example:
                order_requests:
                  - id: 1
                    status: Pendente
                  - id: 2
                    status: Concluído
        401:
          description: Falha na autenticação

  /order-request/{orderRequest}:
    get:
      summary: Obter solicitação de pedido por ID
      description: Este endpoint recupera uma solicitação de pedido pelo seu ID.
      parameters:
        - in: path
          name: orderRequest
          required: true
          schema:
            type: integer
          description: ID da solicitação de pedido a ser recuperada
      responses:
        200:
          description: Dados da solicitação de pedido
          content:
            application/json:
              example:
                id: 1
                status: Pendente
        401:
          description: Falha na autenticação
        404:
          description: Solicitação de pedido não encontrada

    post:
      summary: Criar solicitação de pedido
      description: Este endpoint cria uma nova solicitação de pedido.
      requestBody:
        content:
          application/json:
            example:
              status: Pendente
      responses:
        201:
          description: Solicitação de pedido criada com sucesso
          content:
            application/json:
              example:
                message: Solicitação de pedido criada com sucesso
                order_request_id: 3
        401:
          description: Falha na autenticação

    put:
      summary: Atualizar solicitação de pedido
      description: Este endpoint atualiza os detalhes de uma solicitação de pedido existente.
      parameters:
        - in: path
          name: orderRequest
          required: true
          schema:
            type: integer
          description: ID da solicitação de pedido a ser atualizada
      requestBody:
        content:
          application/json:
            example:
              status: Concluído
      responses:
        200:
          description: Solicitação de pedido atualizada
          content:
            application/json:
              example:
                message: Solicitação de pedido atualizada com sucesso
        401:
          description: Falha na autenticação
        404:
          description: Solicitação de pedido não encontrada

    delete:
      summary: Excluir solicitação de pedido
      description: Este endpoint exclui uma solicitação de pedido existente.
      parameters:
        - in: path
          name: orderRequest
          required: true
          schema:
            type: integer
          description: ID da solicitação de pedido a ser excluída
      responses:
        200:
          description: Solicitação de pedido excluída
          content:
            application/json:
              example:
                message: Solicitação de pedido excluída com sucesso
        401:
          description: Falha na autenticação
        404:
          description: Solicitação de pedido não encontrada
